declare const theme: {
  componentBgColor: string;
  componentBorderColor: string;
  componentBorderRadius: string;
  componentBorderWidth: string;
  componentFocusWidth: string;
  componentPaddingX: string;
  componentPaddingY: string;
  componentSpeed: string;
  componentBoxShadowInner: string;
  componentBoxShadowOuter: string;
  colorPrimary: string;
  colorWhite: string;
  colorNavy: string;
  colorBlue: string;
  colorAqua: string;
  colorTeal: string;
  colorOlive: string;
  colorGreen: string;
  colorLime: string;
  colorYellow: string;
  colorOrange: string;
  colorRed: string;
  colorMaroon: string;
  colorFuchsia: string;
  colorPurple: string;
  colorBlack: string;
  colorGray: string;
  colorSilver: string;
  name: string;
};
export default theme;
